version: "3"
services:
  db:
    image: postgres:10.14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -d postgres -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build:
      context: ./app
    ports:
      - 8000:1323
    command: sh -c "./backend"
    depends_on:
     db:
       condition: service_healthy

  migrate:
    build:
      context: ./migrate
    command: sh -c "./migrate"
    depends_on:
     db:
       condition: service_healthy
